// dashboard/src/components/Sidebar/LocationsList.tsx
import React, { useMemo } from 'react';
import { AgentData } from '../../types';

interface LocationsListProps {
  agents: AgentData[];
  selectedId: string;
  onSelectAgent: (id: string, fly: boolean) => void;
  query: string;
}

interface MachineGroup {
  key: string;
  label: string;
  agents: AgentData[];
  idle: number;
}

const STATUS_TXT: Record<string, [string, string]> = {
  work: ['Working', '#38bdf8'],
  talk: ['Coordinating', '#fbbf24'],
  to: ['Walking', '#c084fc'],
  back: ['Returning', '#c084fc'],
  leaving: ['Leaving', '#f97316'],
  break_play: ['Playground', '#4ade80'],
  break_out: ['Walked out', '#f87171'],
  idle: ['Idle', '#94a3b8'],
};

const trim = (value?: string | null): string => value?.trim() ?? '';

/** Grouping key — device dulu, lalu Orca window sebagai fallback kalau identitas mesin absen. */
function machineGroupKey(agent: AgentData): string {
  const machine = trim(agent.machineId) || trim(agent.machineName);
  if (machine) return `machine:${machine.toLowerCase()}`;
  const orca = trim(agent.orcaName);
  return orca ? `orca:${orca.toLowerCase()}` : '__unknown__';
}

/** Label harus konsisten dengan key: jangan campur orcaName, atau satu device bisa dapat judul milik agent acak. */
function machineGroupLabel(agent: AgentData): string {
  const name = trim(agent.machineName);
  if (name) return name;
  const id = trim(agent.machineId);
  if (id) return id.slice(0, 16);
  const orca = trim(agent.orcaName);
  if (orca) return orca;
  return 'Unknown Device';
}

export const LocationsList: React.FC<LocationsListProps> = ({
  agents,
  selectedId,
  onSelectAgent,
  query,
}) => {
  const groups = useMemo(() => {
    const map = new Map<string, MachineGroup>();

    for (const a of agents) {
      const key = machineGroupKey(a);
      let group = map.get(key);
      if (!group) {
        group = {
          key,
          label: machineGroupLabel(a),
          agents: [],
          idle: 0,
        };
        map.set(key, group);
      }
      group.agents.push(a);
      if (a.mode === 'idle' || a.mode === 'break_play' || a.mode === 'break_out') group.idle++;
    }

    // Sort: machines with more active agents first, then alphabetically
    return [...map.values()].sort((a, b) => {
      const aActive = a.agents.filter(x => x.mode !== 'leaving' && x.mode !== 'break_out').length;
      const bActive = b.agents.filter(x => x.mode !== 'leaving' && x.mode !== 'break_out').length;
      if (bActive !== aActive) return bActive - aActive;
      return a.label.localeCompare(b.label);
    });
  }, [agents]);

  const filtered = useMemo(() => {
    if (!query) return groups;
    const q = query.toLowerCase();
    return groups
      .map(g => ({
        ...g,
        agents: g.agents.filter(a =>
          (a.name + a.task + a.role + g.label).toLowerCase().includes(q)
        ),
      }))
      .filter(g => g.agents.length > 0);
  }, [groups, query]);

  if (filtered.length === 0) {
    return <p style={{ color: '#64748b', fontSize: '.8rem', padding: '12px' }}>Tidak ketemu.</p>;
  }

  const totalMachines = filtered.length;
  const totalAgents = filtered.reduce((s, g) => s + g.agents.length, 0);

  return (
    <div>
      <div style={{
        padding: '8px 12px',
        fontSize: '.72rem',
        color: '#94a3b8',
        borderBottom: '1px solid rgba(148,163,184,0.12)',
        display: 'flex',
        justifyContent: 'space-between',
      }}>
        <span>{totalMachines} device{totalMachines !== 1 ? 's' : ''}</span>
        <span>{totalAgents} agent{totalAgents !== 1 ? 's' : ''}</span>
      </div>

      {filtered.map((group) => {
        const activeCount = group.agents.filter(
          a => a.mode !== 'leaving' && a.mode !== 'break_out'
        ).length;

        return (
          <div
            key={group.key}
            style={{
              borderBottom: '1px solid rgba(148,163,184,0.08)',
              padding: '10px 12px 6px',
            }}
          >
            {/* Machine header */}
            <div style={{
              display: 'flex',
              alignItems: 'center',
              gap: '8px',
              marginBottom: '6px',
            }}>
              <span style={{ fontSize: '1rem' }}>💻</span>
              <div style={{ flex: 1 }}>
                <div style={{
                  fontWeight: 600,
                  fontSize: '.82rem',
                  color: '#e2e8f0',
                }}>
                  {group.label}
                </div>
                <div style={{
                  fontSize: '.68rem',
                  color: '#64748b',
                  fontFamily: "'JetBrains Mono', monospace",
                  marginTop: '1px',
                }}>
                  {activeCount > 0 ? (
                    <>
                      <span style={{ color: '#4ade80' }}>{activeCount} active</span>
                      {group.idle > 0 && (
                        <>, <span style={{ color: '#fbbf24' }}>{group.idle} idle</span></>
                      )}
                    </>
                  ) : (
                    <span style={{ color: '#64748b' }}>all offline</span>
                  )}
                  <span> · {group.agents.length} agent{group.agents.length !== 1 ? 's' : ''}</span>
                </div>
              </div>
            </div>

            {/* Agent list under this machine */}
            {group.agents.map((a) => {
              const isSelected = a.id === selectedId;
              const [statusTxt, statusCol] = STATUS_TXT[a.mode] || STATUS_TXT.work;

              return (
                <div
                  key={a.id}
                  onClick={() => onSelectAgent(a.id, true)}
                  style={{
                    display: 'flex',
                    alignItems: 'center',
                    gap: '8px',
                    padding: '5px 8px',
                    marginLeft: '20px',
                    borderRadius: '6px',
                    cursor: 'pointer',
                    background: isSelected ? 'rgba(56,189,248,0.1)' : 'transparent',
                    transition: 'background .15s',
                  }}
                >
                  <span style={{ fontSize: '.9rem' }}>{a.av}</span>
                  <div style={{ flex: 1, minWidth: 0 }}>
                    <div style={{
                      fontSize: '.78rem',
                      color: '#e2e8f0',
                      fontWeight: isSelected ? 600 : 400,
                      whiteSpace: 'nowrap',
                      overflow: 'hidden',
                      textOverflow: 'ellipsis',
                    }}>
                      {a.name}
                      {a.project && (
                        <span style={{
                          fontSize: '.65rem',
                          color: '#64748b',
                          marginLeft: '6px',
                        }}>
                          {a.project}
                        </span>
                      )}
                    </div>
                    <div style={{
                      fontSize: '.66rem',
                      color: statusCol,
                      whiteSpace: 'nowrap',
                      overflow: 'hidden',
                      textOverflow: 'ellipsis',
                    }}>
                      {statusTxt} — {a.task}
                    </div>
                  </div>
                  {a.realSessionId && (
                    <span style={{
                      fontFamily: "'JetBrains Mono', monospace",
                      fontSize: '.58rem',
                      color: '#7dd3fc',
                      background: 'rgba(56,189,248,0.1)',
                      padding: '1px 4px',
                      borderRadius: '3px',
                      border: '1px solid rgba(56,189,248,0.2)',
                      flexShrink: 0,
                    }}>
                      #{a.realSessionId.slice(0, 6)}
                    </span>
                  )}
                </div>
              );
            })}
          </div>
        );
      })}
    </div>
  );
};

// dashboard/src/app/shared/team/locations-list.component.ts
// ============================================================
// LocationsListComponent — port 1:1 Sidebar/LocationsList.tsx
// Roster di-group per device (machineId/machineName → orcaName → unknown).
// ============================================================

import { Component, Input, inject } from '@angular/core';
import type { AgentData } from '../../core/models/types';
import { UiStateService } from '../../core/services/ui-state.service';

interface MachineGroup {
  key: string;
  label: string;
  agents: AgentData[];
  idle: number;
}

const STATUS_TXT: Record<string, [string, string]> = {
  work: ['Working', '#38bdf8'],
  talk: ['Coordinating', '#fbbf24'],
  to: ['Walking', '#c084fc'],
  back: ['Returning', '#c084fc'],
  leaving: ['Leaving', '#f97316'],
  break_play: ['Playground', '#4ade80'],
  break_out: ['Walked out', '#f87171'],
  idle: ['Idle', '#94a3b8'],
};

const trim = (value?: string | null): string => value?.trim() ?? '';

/** Grouping key — device dulu, lalu Orca window sebagai fallback kalau identitas mesin absen. */
function machineGroupKey(agent: AgentData): string {
  const machine = trim(agent.machineId) || trim(agent.machineName);
  if (machine) return `machine:${machine.toLowerCase()}`;
  const orca = trim(agent.orcaName);
  return orca ? `orca:${orca.toLowerCase()}` : '__unknown__';
}

/** Label harus konsisten dengan key: jangan campur orcaName, atau satu device bisa dapat judul milik agent acak. */
function machineGroupLabel(agent: AgentData): string {
  const name = trim(agent.machineName);
  if (name) return name;
  const id = trim(agent.machineId);
  if (id) return id.slice(0, 16);
  const orca = trim(agent.orcaName);
  if (orca) return orca;
  return 'Unknown Device';
}

const isActive = (a: AgentData): boolean => a.mode !== 'leaving' && a.mode !== 'break_out';

@Component({
  selector: 'locations-list',
  standalone: true,
  template: `
    @if (filtered().length === 0) {
      <p class="pane-empty">Tidak ketemu.</p>
    } @else {
      <div>
        <div class="loc-summary">
          <span>{{ filtered().length }} device{{ filtered().length !== 1 ? 's' : '' }}</span>
          <span>{{ totalAgents() }} agent{{ totalAgents() !== 1 ? 's' : '' }}</span>
        </div>

        @for (group of filtered(); track group.key) {
          <div class="loc-group">
            <div class="loc-head">
              <span class="ico">💻</span>
              <div class="grow">
                <div class="loc-label">{{ group.label }}</div>
                <div class="loc-sub">
                  @if (activeOf(group) > 0) {
                    <span class="active">{{ activeOf(group) }} active</span>
                    @if (group.idle > 0) {
                      , <span class="idle">{{ group.idle }} idle</span>
                    }
                  } @else {
                    <span style="color:#64748b">all offline</span>
                  }
                  <span> · {{ group.agents.length }} agent{{ group.agents.length !== 1 ? 's' : '' }}</span>
                </div>
              </div>
            </div>

            @for (a of group.agents; track a.id) {
              <div
                class="loc-agent"
                [class.sel]="a.id === ui.selectedId()"
                (click)="ui.selectAgent(a.id, true)"
              >
                <span class="av">{{ a.av }}</span>
                <div class="body">
                  <div class="loc-agent-name">
                    {{ a.name }}
                    @if (a.project) { <span class="loc-proj">{{ a.project }}</span> }
                  </div>
                  <div class="loc-status" [style.color]="statusColor(a)">
                    {{ statusText(a) }} — {{ a.task }}
                  </div>
                </div>
                @if (a.realSessionId) {
                  <span class="loc-sid">#{{ a.realSessionId.slice(0, 6) }}</span>
                }
              </div>
            }
          </div>
        }
      </div>
    }
  `,
})
export class LocationsListComponent {
  @Input() agents: AgentData[] = [];
  protected ui = inject(UiStateService);

  /** Grup per device, urut: paling banyak agent aktif dulu lalu alfabet. */
  private groups(): MachineGroup[] {
    const map = new Map<string, MachineGroup>();
    for (const a of this.agents) {
      const key = machineGroupKey(a);
      let group = map.get(key);
      if (!group) {
        group = { key, label: machineGroupLabel(a), agents: [], idle: 0 };
        map.set(key, group);
      }
      group.agents.push(a);
      if (a.mode === 'idle' || a.mode === 'break_play' || a.mode === 'break_out') group.idle++;
    }
    return [...map.values()].sort((x, y) => {
      const aActive = x.agents.filter(isActive).length;
      const bActive = y.agents.filter(isActive).length;
      if (bActive !== aActive) return bActive - aActive;
      return x.label.localeCompare(y.label);
    });
  }

  filtered(): MachineGroup[] {
    const groups = this.groups();
    const q = this.ui.query();
    if (!q) return groups;
    const lq = q.toLowerCase();
    return groups
      .map((g) => ({
        ...g,
        agents: g.agents.filter((a) =>
          (a.name + a.task + a.role + g.label).toLowerCase().includes(lq),
        ),
      }))
      .filter((g) => g.agents.length > 0);
  }

  totalAgents(): number {
    return this.filtered().reduce((s, g) => s + g.agents.length, 0);
  }

  activeOf(group: MachineGroup): number {
    return group.agents.filter(isActive).length;
  }

  statusText(a: AgentData): string {
    return (STATUS_TXT[a.mode] ?? STATUS_TXT['work'])[0];
  }
  statusColor(a: AgentData): string {
    return (STATUS_TXT[a.mode] ?? STATUS_TXT['work'])[1];
  }
}
