// dashboard/src/components/Sidebar/TasksList.tsx
import React from 'react';
import { agentDeviceLabel, agentIdentitySearchText } from '../../lib/agent-identity';
import { AgentData } from '../../types';

interface TasksListProps {
  agents: AgentData[];
  selectedId: string;
  onSelectAgent: (id: string, fly: boolean) => void;
  query: string;
}

export const TasksList: React.FC<TasksListProps> = ({
  agents,
  selectedId,
  onSelectAgent,
  query,
}) => {
  const filtered = agents.filter((a) =>
    (a.name + a.task + agentIdentitySearchText(a)).toLowerCase().includes(query.toLowerCase())
  );

  return (
    <div>
      {filtered.map((a) => {
        const isSelected = a.id === selectedId;
        const deviceLabel = agentDeviceLabel(a);
        return (
          <div
            key={a.id}
            className={`row ${isSelected ? 'sel' : ''}`}
            onClick={() => onSelectAgent(a.id, true)}
          >
            <div className="t1">
              <div className="av2">{a.av}</div>
              <div className="n">{a.task}</div>
            </div>
            <div className="tk2">
              {a.name} · {a.role}{deviceLabel ? ` · 🏢 ${deviceLabel}` : ''}
            </div>
            <div className="pbar">
              <i style={{ width: `${a.prog}%` }}></i>
            </div>
            {a.subs.map((s, idx) => (
              <div key={idx} className={`sub ${idx < a.subIdx ? 'done' : ''}`}>
                {idx < a.subIdx ? '✅' : '◽'} {s}
              </div>
            ))}
          </div>
        );
      })}
    </div>
  );
};

// dashboard/src/app/shared/team/tasks-list.component.ts
// ============================================================
// TasksListComponent — port 1:1 Sidebar/TasksList.tsx
// ============================================================

import { Component, Input, inject } from '@angular/core';
import type { AgentData } from '../../core/models/types';
import { UiStateService } from '../../core/services/ui-state.service';
import { agentDeviceLabel, agentIdentitySearchText } from '../../core/utils/agent-identity';

@Component({
  selector: 'tasks-list',
  standalone: true,
  template: `
    <div>
      @for (a of filtered(); track a.id) {
        <div class="row" [class.sel]="a.id === ui.selectedId()" (click)="ui.selectAgent(a.id, true)">
          <div class="t1">
            <div class="av2">{{ a.av }}</div>
            <div class="n">{{ a.task }}</div>
          </div>
          <div class="tk2">{{ a.name }} · {{ a.role }}{{ deviceSuffix(a) }}</div>
          <div class="pbar"><i [style.width.%]="a.prog"></i></div>
          @for (s of a.subs; track $index) {
            <div class="sub" [class.done]="$index < a.subIdx">
              {{ $index < a.subIdx ? '✅' : '◽' }} {{ s }}
            </div>
          }
        </div>
      }
    </div>
  `,
})
export class TasksListComponent {
  @Input() agents: AgentData[] = [];
  protected ui = inject(UiStateService);

  filtered(): AgentData[] {
    const q = this.ui.query().toLowerCase();
    return this.agents.filter((a) =>
      (a.name + a.task + agentIdentitySearchText(a)).toLowerCase().includes(q),
    );
  }

  deviceSuffix(a: AgentData): string {
    const d = agentDeviceLabel(a);
    return d ? ` · 🏢 ${d}` : '';
  }
}
