// dashboard/src/app/shared/feed/feed-list.component.ts
// ============================================================
// FeedListComponent — port 1:1 Sidebar/FeedList.tsx
// ============================================================

import { Component, Input, inject } from '@angular/core';
import type { FeedEvent } from '../../core/models/types';
import { UiStateService } from '../../core/services/ui-state.service';

const ICONS: Record<string, string> = {
  task: '✅',
  tool: '🔧',
  chat: '💬',
  move: '🚶',
  sys: '☕',
};

@Component({
  selector: 'feed-list',
  standalone: true,
  template: `
    @if (list().length === 0) {
      <p class="pane-empty">Feed kosong.</p>
    } @else {
      <div>
        @for (e of list(); track $index) {
          <div class="ev">
            <div class="ic">{{ icon(e) }}</div>
            <div>
              <div class="tx">
                <b>{{ e.who }}</b> <span [class]="'k-' + e.kind">{{ e.kind }}</span> — {{ e.text }}
                @if (e.code) {
                  <br />
                  <code>{{ e.code }}</code>
                }
              </div>
              <div class="mt">#{{ e.n }} · {{ e.t }}</div>
            </div>
          </div>
        }
      </div>
    }
  `,
})
export class FeedListComponent {
  @Input() events: FeedEvent[] = [];
  private ui = inject(UiStateService);

  list(): FeedEvent[] {
    const kind = this.ui.feedKind();
    const q = this.ui.query();
    return this.events
      .filter(
        (e) =>
          (kind === 'all' || e.kind === kind) &&
          (!q || (e.who + e.text).toLowerCase().includes(q)),
      )
      .slice(0, 60);
  }

  icon(e: FeedEvent): string {
    return ICONS[e.kind] ?? '•';
  }
}

// dashboard/src/components/Sidebar/FeedList.tsx
import React from 'react';
import { FeedEvent } from '../../types';

interface FeedListProps {
  events: FeedEvent[];
  feedKind: 'all' | 'task' | 'tool' | 'chat' | 'move';
  query: string;
}

const ICONS: Record<string, string> = {
  task: '✅',
  tool: '🔧',
  chat: '💬',
  move: '🚶',
  sys: '☕',
};

export const FeedList: React.FC<FeedListProps> = ({ events, feedKind, query }) => {
  const list = events.filter(
    (e) =>
      (feedKind === 'all' || e.kind === feedKind) &&
      (!query || (e.who + e.text).toLowerCase().includes(query.toLowerCase()))
  );

  if (list.length === 0) {
    return <p style={{ color: '#64748b', fontSize: '.8rem', padding: '12px' }}>Feed kosong.</p>;
  }

  return (
    <div>
      {list.slice(0, 60).map((e, idx) => (
        <div key={idx} className="ev">
          <div className="ic">{ICONS[e.kind] || '•'}</div>
          <div>
            <div className="tx">
              <b>{e.who}</b> <span className={`k-${e.kind}`}>{e.kind}</span> — {e.text}
              {e.code && (
                <>
                  <br />
                  <code>{e.code}</code>
                </>
              )}
            </div>
            <div className="mt">
              #{e.n} · {e.t}
            </div>
          </div>
        </div>
      ))}
    </div>
  );
};
