// dashboard/src/app/shared/sidebar/sidebar.component.ts
// ============================================================
// SidebarComponent — port 1:1 components/Sidebar/Sidebar.tsx
// ============================================================

import { Component, inject } from '@angular/core';
import { UiStateService } from '../../core/services/ui-state.service';
import { OfficeStateService } from '../../core/services/office-state.service';
import { FloorStatsComponent } from './floor-stats.component';
import { SelectedCardComponent } from './selected-card.component';
import { SidebarTabsComponent } from './sidebar-tabs.component';
import { TeamListComponent } from '../team/team-list.component';
import { LocationsListComponent } from '../team/locations-list.component';
import { TasksListComponent } from '../team/tasks-list.component';
import { ToolsListComponent } from '../feed/tools-list.component';
import { FeedListComponent } from '../feed/feed-list.component';
import { RealtimeLogsComponent } from '../logs/realtime-logs.component';
import { BillingPanelComponent } from '../billing/billing-panel.component';

@Component({
  selector: 'app-sidebar',
  standalone: true,
  imports: [
    FloorStatsComponent,
    SelectedCardComponent,
    SidebarTabsComponent,
    TeamListComponent,
    LocationsListComponent,
    TasksListComponent,
    ToolsListComponent,
    FeedListComponent,
    RealtimeLogsComponent,
    BillingPanelComponent,
  ],
  template: `
    <aside class="side">
      <div class="side-head">
        <h1>
          ☕ Floor manager
          <span style="font-weight:400;color:#64748b;font-size:.72rem">· live state</span>
        </h1>
        <p>Semua bubble, tool calls, tasks &amp; tagihan token — satu sumber state terintegrasi.</p>

        <floor-stats
          [working]="ui.workingCount()"
          [walking]="ui.walkingCount()"
          [idle]="ui.idleCount()"
          [done]="ui.doneCount()"
        />

        <selected-card [agent]="ui.selectedAgent()" />
      </div>

      <sidebar-tabs />

      <div class="search">
        <input
          placeholder="🔍 cari tim / task / tool / menu…"
          [value]="ui.query()"
          (input)="ui.setQuery($any($event.target).value)"
        />
      </div>

      <div class="pane">
        @switch (ui.tab()) {
          @case ('locations') { <locations-list [agents]="ui.agents()" /> }
          @case ('team') { <team-list [agents]="ui.agents()" /> }
          @case ('tasks') { <tasks-list [agents]="ui.agents()" /> }
          @case ('tools') { <tools-list [events]="ui.events()" /> }
          @case ('feed') { <feed-list [events]="ui.events()" /> }
          @case ('logs') { <realtime-logs [logs]="office.recentLogs()" /> }
          @case ('bill') { <billing-panel [billing]="office.billing()" /> }
        }
      </div>
    </aside>
  `,
})
export class SidebarComponent {
  protected ui = inject(UiStateService);
  protected office = inject(OfficeStateService);
}

// dashboard/src/components/Sidebar/Sidebar.tsx
import React, { useState } from 'react';
import { AgentData, BillingSummary, FeedEvent, LogEntry } from '../../types';
import { FloorStats } from './FloorStats';
import { SelectedCard } from './SelectedCard';
import { SidebarTabs } from './SidebarTabs';
import { TeamList } from './TeamList';
import { LocationsList } from './LocationsList';
import { TasksList } from './TasksList';
import { ToolsList } from './ToolsList';
import { FeedList } from './FeedList';
import { BillingPanel } from './BillingPanel';
import { RealtimeLogs } from '../RealtimeLogs';

interface SidebarProps {
  agents: AgentData[];
  selectedId: string;
  onSelectAgent: (id: string, fly: boolean) => void;
  onKillAgent: (agent: AgentData) => void;
  events: FeedEvent[];
  logs: LogEntry[];
  billing: BillingSummary;
  stats: {
    working: number;
    walking: number;
    idle: number;
    done: number;
  };
}

export const Sidebar: React.FC<SidebarProps> = ({
  agents,
  selectedId,
  onSelectAgent,
  onKillAgent,
  events,
  logs,
  billing,
  stats,
}) => {
  const [tab, setTab] = useState<'team' | 'locations' | 'tasks' | 'tools' | 'feed' | 'logs' | 'bill'>('team');
  const [feedKind, setFeedKind] = useState<'all' | 'task' | 'tool' | 'chat' | 'move'>('all');
  const [query, setQuery] = useState('');

  const selectedAgent = agents.find((a) => a.id === selectedId);

  return (
    <aside className="side">
      <div className="side-head">
        <h1>
          ☕ Floor manager <span style={{ fontWeight: 400, color: '#64748b', fontSize: '.72rem' }}>· live state</span>
        </h1>
        <p>Semua bubble, tool calls, tasks & tagihan token — satu sumber state terintegrasi.</p>

        <FloorStats
          workingCount={stats.working}
          walkingCount={stats.walking}
          idleCount={stats.idle}
          doneCount={stats.done}
        />

        <SelectedCard agent={selectedAgent} />
      </div>

      <SidebarTabs
        activeTab={tab}
        onSetTab={setTab}
        feedKind={feedKind}
        onSetFeedKind={setFeedKind}
      />

      <div className="search">
        <input
          placeholder="🔍 cari tim / task / tool / menu…"
          value={query}
          onChange={(e) => setQuery(e.target.value)}
        />
      </div>

      <div className="pane">
        {tab === 'locations' && (
          <LocationsList
            agents={agents}
            selectedId={selectedId}
            onSelectAgent={onSelectAgent}
            query={query}
          />
        )}
        {tab === 'team' && (
          <TeamList
            agents={agents}
            selectedId={selectedId}
            onSelectAgent={onSelectAgent}
            onKillAgent={onKillAgent}
            query={query}
          />
        )}
        {tab === 'tasks' && (
          <TasksList
            agents={agents}
            selectedId={selectedId}
            onSelectAgent={onSelectAgent}
            query={query}
          />
        )}
        {tab === 'tools' && <ToolsList events={events} query={query} />}
        {tab === 'feed' && (
          <FeedList events={events} feedKind={feedKind} query={query} />
        )}
        {tab === 'logs' && <RealtimeLogs logs={logs} />}
        {tab === 'bill' && (
          <BillingPanel
            billing={billing}
            query={query}
            onSelectUser={(sessionId) => {
              const agent = agents.find((a) => a.realSessionId === sessionId);
              if (agent) onSelectAgent(agent.id, true);
            }}
          />
        )}
      </div>
    </aside>
  );
};
