// dashboard/src/components/Sidebar/FloorStats.tsx
import React from 'react';

interface FloorStatsProps {
  workingCount: number;
  walkingCount: number;
  idleCount: number;
  doneCount: number;
}

export const FloorStats: React.FC<FloorStatsProps> = ({
  workingCount,
  walkingCount,
  idleCount,
  doneCount,
}) => {
  return (
    <div className="stats">
      <div className="stat">
        <b style={{ color: '#38bdf8' }}>{workingCount}</b>
        <span>working</span>
      </div>
      <div className="stat">
        <b style={{ color: '#c084fc' }}>{walkingCount}</b>
        <span>walking</span>
      </div>
      <div className="stat">
        <b style={{ color: '#fbbf24' }}>{idleCount}</b>
        <span>idle/break</span>
      </div>
      <div className="stat">
        <b style={{ color: '#4ade80' }}>{doneCount}</b>
        <span>tasks done</span>
      </div>
    </div>
  );
};

// dashboard/src/app/shared/sidebar/floor-stats.component.ts
// ============================================================
// FloorStatsComponent — port 1:1 Sidebar/FloorStats.tsx
// ============================================================

import { Component, Input } from '@angular/core';

@Component({
  selector: 'floor-stats',
  standalone: true,
  template: `
    <div class="stats">
      <div class="stat"><b style="color:#38bdf8">{{ working }}</b><span>working</span></div>
      <div class="stat"><b style="color:#c084fc">{{ walking }}</b><span>walking</span></div>
      <div class="stat"><b style="color:#fbbf24">{{ idle }}</b><span>idle/break</span></div>
      <div class="stat"><b style="color:#4ade80">{{ done }}</b><span>tasks done</span></div>
    </div>
  `,
})
export class FloorStatsComponent {
  @Input() working = 0;
  @Input() walking = 0;
  @Input() idle = 0;
  @Input() done = 0;
}
