// dashboard/src/components/Sidebar/SelectedCard.tsx
import React from 'react';
import { agentDeviceLabel, agentWorkspaceLabel } from '../../lib/agent-identity';
import { AgentData } from '../../types';

interface SelectedCardProps {
  agent?: AgentData;
}

export const SelectedCard: React.FC<SelectedCardProps> = ({ agent }) => {
  const deviceLabel = agent ? agentDeviceLabel(agent) : null;
  const workspaceLabel = agent ? agentWorkspaceLabel(agent) : null;

  if (!agent) {
    return (
      <div className="selcard">
        <div className="av">☕</div>
        <div>
          <div className="nm">ORCA24</div>
          <div className="rl">Klik bubble / nama di list untuk fokus kamera.</div>
        </div>
      </div>
    );
  }

  return (
    <div className="selcard">
      <div className="av">{agent.av}</div>
      <div>
        <div className="nm" style={{ display: 'flex', alignItems: 'center', gap: '6px' }}>
          <span>{agent.name}</span>
          {agent.realSessionId && (
            <span
              style={{
                fontFamily: "'JetBrains Mono', monospace",
                fontSize: '0.65rem',
                color: '#7dd3fc',
                background: 'rgba(56,189,248,0.12)',
                padding: '1px 6px',
                borderRadius: '4px',
                border: '1px solid rgba(56,189,248,0.3)'
              }}
              title={agent.realSessionId}
            >
              #{agent.realSessionId.slice(0, 8)}
            </span>
          )}
        </div>
        <div className="rl">
          {agent.role} · {agent.mode} · {agent.task}
        </div>
        {agent.project && (
          <div
            className="rl"
            style={{
              marginTop: '3px',
              fontFamily: "'JetBrains Mono', monospace",
              fontSize: '0.62rem',
              color: 'var(--wood)'
            }}
            title={`Project git: ${agent.project}`}
          >
            📁 {agent.project}
          </div>
        )}
        {deviceLabel && (
          <div
            className="rl"
            style={{
              marginTop: '3px',
              fontFamily: "'JetBrains Mono', monospace",
              fontSize: '0.62rem',
              color: '#7dd3fc'
            }}
            title={agent.machineId ? `Machine ID: ${agent.machineId}` : 'Device'}
          >
            🏢 {deviceLabel}
          </div>
        )}
        {workspaceLabel && (
          <div
            className="rl"
            style={{
              marginTop: '3px',
              fontFamily: "'JetBrains Mono', monospace",
              fontSize: '0.62rem',
              color: '#a5b4fc'
            }}
            title={agent.orcaPane ? `Orca pane: ${agent.orcaPane}` : 'Orca workspace'}
          >
            🐋 {workspaceLabel}
          </div>
        )}
      </div>
    </div>
  );
};

// dashboard/src/app/shared/sidebar/selected-card.component.ts
// ============================================================
// SelectedCardComponent — port 1:1 Sidebar/SelectedCard.tsx
// ============================================================

import { Component, Input } from '@angular/core';
import type { AgentData } from '../../core/models/types';
import { agentDeviceLabel, agentWorkspaceLabel } from '../../core/utils/agent-identity';

@Component({
  selector: 'selected-card',
  standalone: true,
  template: `
    @if (!agent) {
      <div class="selcard">
        <div class="av">☕</div>
        <div>
          <div class="nm">ORCA24</div>
          <div class="rl">Klik bubble / nama di list untuk fokus kamera.</div>
        </div>
      </div>
    } @else {
      <div class="selcard">
        <div class="av">{{ agent.av }}</div>
        <div>
          <div class="nm">
            <span>{{ agent.name }}</span>
            @if (agent.realSessionId) {
              <span class="sid" [title]="agent.realSessionId">#{{ sidShort() }}</span>
            }
          </div>
          <div class="rl">{{ agent.role }} · {{ agent.mode }} · {{ agent.task }}</div>
          @if (agent.project) {
            <div class="rl mono-wood" [title]="'Project git: ' + agent.project">📁 {{ agent.project }}</div>
          }
          @if (deviceLabel()) {
            <div class="rl mono-cyan" [title]="machineTitle()">🏢 {{ deviceLabel() }}</div>
          }
          @if (workspaceLabel()) {
            <div class="rl mono-indigo" [title]="paneTitle()">🐋 {{ workspaceLabel() }}</div>
          }
        </div>
      </div>
    }
  `,
})
export class SelectedCardComponent {
  @Input() agent?: AgentData;

  sidShort(): string {
    return (this.agent?.realSessionId ?? '').slice(0, 8);
  }
  deviceLabel(): string | null {
    return this.agent ? agentDeviceLabel(this.agent) : null;
  }
  workspaceLabel(): string | null {
    return this.agent ? agentWorkspaceLabel(this.agent) : null;
  }
  machineTitle(): string {
    return this.agent?.machineId ? `Machine ID: ${this.agent.machineId}` : 'Device';
  }
  paneTitle(): string {
    return this.agent?.orcaPane ? `Orca pane: ${this.agent.orcaPane}` : 'Orca workspace';
  }
}
