// dashboard/src/components/Sidebar/SidebarTabs.tsx
import React from 'react';

interface SidebarTabsProps {
  activeTab: 'team' | 'locations' | 'tasks' | 'tools' | 'feed' | 'logs' | 'bill';
  onSetTab: (tab: 'team' | 'locations' | 'tasks' | 'tools' | 'feed' | 'logs' | 'bill') => void;
  feedKind: 'all' | 'task' | 'tool' | 'chat' | 'move';
  onSetFeedKind: (kind: 'all' | 'task' | 'tool' | 'chat' | 'move') => void;
}

export const SidebarTabs: React.FC<SidebarTabsProps> = ({
  activeTab,
  onSetTab,
  feedKind,
  onSetFeedKind,
}) => {
  return (
    <>
      <div className="tabs">
        <button
          className={activeTab === 'team' ? 'active' : ''}
          onClick={() => onSetTab('team')}
        >
          Team
        </button>
        <button
          className={activeTab === 'locations' ? 'active' : ''}
          onClick={() => onSetTab('locations')}
          title="Group agent by device / laptop"
        >
          📍 Locs
        </button>
        <button
          className={activeTab === 'tasks' ? 'active' : ''}
          onClick={() => onSetTab('tasks')}
        >
          Tasks
        </button>
        <button
          className={activeTab === 'tools' ? 'active' : ''}
          onClick={() => onSetTab('tools')}
        >
          Tools
        </button>
        <button
          className={activeTab === 'feed' ? 'active' : ''}
          onClick={() => onSetTab('feed')}
        >
          Feed
        </button>
        <button
          className={activeTab === 'logs' ? 'active' : ''}
          onClick={() => onSetTab('logs')}
        >
          Logs
        </button>
        <button
          className={activeTab === 'bill' ? 'active' : ''}
          onClick={() => onSetTab('bill')}
          title="Tagihan token & biaya per pegawai"
        >
          ☕ Bill
        </button>
      </div>

      {activeTab === 'feed' && (
        <div className="chips">
          {(['all', 'task', 'tool', 'chat', 'move'] as const).map((k) => (
            <button
              key={k}
              className={`chip ${feedKind === k ? 'active' : ''}`}
              onClick={() => onSetFeedKind(k)}
            >
              {k === 'all' ? 'All' : k.toUpperCase()}
            </button>
          ))}
        </div>
      )}
    </>
  );
};

// dashboard/src/app/shared/sidebar/sidebar-tabs.component.ts
// ============================================================
// SidebarTabsComponent — port 1:1 Sidebar/SidebarTabs.tsx
// 7 tab + chip filter khusus Feed.
// ============================================================

import { Component, inject } from '@angular/core';
import { UiStateService } from '../../core/services/ui-state.service';

@Component({
  selector: 'sidebar-tabs',
  standalone: true,
  template: `
    <div class="tabs">
      <button [class.active]="ui.tab() === 'team'" (click)="ui.setTab('team')">Team</button>
      <button
        [class.active]="ui.tab() === 'locations'"
        (click)="ui.setTab('locations')"
        title="Group agent by device / laptop"
      >
        📍 Locs
      </button>
      <button [class.active]="ui.tab() === 'tasks'" (click)="ui.setTab('tasks')">Tasks</button>
      <button [class.active]="ui.tab() === 'tools'" (click)="ui.setTab('tools')">Tools</button>
      <button [class.active]="ui.tab() === 'feed'" (click)="ui.setTab('feed')">Feed</button>
      <button [class.active]="ui.tab() === 'logs'" (click)="ui.setTab('logs')">Logs</button>
      <button
        [class.active]="ui.tab() === 'bill'"
        (click)="ui.setTab('bill')"
        title="Tagihan token & biaya per pegawai"
      >
        ☕ Bill
      </button>
    </div>

    @if (ui.tab() === 'feed') {
      <div class="chips">
        @for (k of feedKinds; track k) {
          <button class="chip" [class.active]="ui.feedKind() === k" (click)="ui.setFeedKind(k)">
            {{ k === 'all' ? 'All' : k.toUpperCase() }}
          </button>
        }
      </div>
    }
  `,
})
export class SidebarTabsComponent {
  protected ui = inject(UiStateService);
  protected readonly feedKinds = ['all', 'task', 'tool', 'chat', 'move'] as const;
}
